Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.hostname = "node104"
  config.vm.network "private_network", ip: "10.1.100.104"
  # 虚拟机配置
  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.memory = "16384"
	vb.cpus = 2
  end
  # 初始化安装脚本
  config.vm.provision "shell", inline: <<-SHELL
    yum update
    yum install -y vim wget
	sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/'  /etc/ssh/sshd_config
	systemctl restart sshd	
	# 关闭防火墙
	systemctl stop firewalld.service 
	systemctl disable firewalld.service
	# 关闭selinux
	sed -i 's/enforcing/disabled/' /etc/selinux/config
	sysctl --system
	# 开启时间同步
	yum install ntpdate -y 
	ntpdate time.windows.com
	# 时区
	timedatectl set-timezone Asia/Shanghai
	# 安装lrzsz命令
	yum install -y lrzsz
	# 修改源为阿里云
	mv /etc/yum.repos.d/CentOS-Base.repo /etc/yum.repos.d/CentOS-Base.repo.backup
	wget -O /etc/yum.repos.d/CentOS-Base.repo https://mirrors.aliyun.com/repo/Centos-7.repo
	yum makecache
  SHELL
end